#APACHE
server:
  port: 8080

#REFRESH_SCOPE CONFIG
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

#EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-lab-dekra-lab-dekra.e4ff.pro-eu-west-1.openshiftapps.com/eureka/
